<?php
$translate = $this->plugin('translate');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('vendor/chosen-js/chosen.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro|Lato:400,400italic,700,700italic');
$this->headScript()->prependFile($this->assetUrl('js/admin.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/chosen-options.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/chosen-js/chosen.jquery.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();

$escape = $this->plugin('escapeHtml');
$siteNav = (string) $this->navigation('Laminas\Navigation\AdminSite')->menu();
$resourceNav = (string) $this->navigation('Laminas\Navigation\AdminResource')->menu();
$adminNav = (string) $this->navigation('Laminas\Navigation\AdminGlobal')->menu();
$moduleNav = (string) $this->navigation('Laminas\Navigation\AdminModule')->menu();
$this->trigger('view.layout');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <?php echo $this->htmlElement('body'); ?>
        <a href="#content" class="skip"><?php echo $translate('Skip to main content'); ?></a>
        <div class="flex">
            <header>
                <div class="logo"><a href="<?php echo $this->url('admin'); ?>"><?php echo $this->setting('installation_title', 'Omeka S'); ?></a></div>
                <div id="mobile-nav">
                    <a href="#" class="o-icon-menu button"><span class="screen-reader-text"><?php echo $translate('Navigation menu'); ?></span></a>
                    <a href="#" class="o-icon-search button"><span class="screen-reader-text"><?php echo $translate('Search site'); ?></span></a>
                    <a href="#" class="o-icon-user button"><span class="screen-reader-text"><?php echo $translate('User menu'); ?></span></a>
                </div>
                <div id="user">
                    <?php if ($this->identity()): ?>
                    <p class="user-id"><?php echo sprintf($translate('Signed in as %s'),  '<a href="' . $this->url('admin/id', [
                        'controller' => 'user',
                        'id' => $this->identity()->getId(),
                    ]) . '">' . $escape($this->identity()->getName()) . '</a>'); ?></p>
                    <p class="logout"><a href="<?php echo $this->url('logout'); ?>"><?php echo $translate('Logout'); ?></a></p>
                    <?php else: ?>
                    <p><?php echo $translate('not logged in'); ?></p>
                    <?php endif; ?>
                </div>
                <div id="search">
                    <form action="<?php echo $escape($this->url('admin/default', ['controller' => 'item', 'action' => 'browse'])); ?>">
                        <?php $searchValue = isset($_GET['property'][0]["text"]) ? $_GET['property'][0]["text"] : ''; ?>
                        <input type="text" placeholder="<?php echo $translate('Search'); ?>"
        aria-label="<?php echo $translate('Search'); ?>" name="property[0][text]" value="<?php echo $escape($searchValue); ?>">
                        <button type="submit"><?php echo $translate('Search'); ?></button>
                        <input type="hidden" name="property[0][joiner]" value="and" />
                        <input type="hidden" name="property[0][property]" value="" />
                        <input type="hidden" name="property[0][type]" value="in" />
                        <?php $searchValue = isset($_GET['fulltext_search']) ? $_GET['fulltext_search'] : ''; ?>
                    </form>
                </div>
                <nav id="menu" role="navigation">
                    <?php echo $siteNav; ?>
                    <?php if (isset($site)): ?>
                    <nav id="site-nav">
                        <h5><?php echo $site->link($site->title(), 'show'); ?></h5>
                        <?php echo $this->hyperlink('', $site->siteUrl(), ['class' => 'o-icon-external public', 'target' => '_blank', 'title' => $translate('View public site')]); ?>
                    <?php echo $site->adminNav()->menu(); ?>
                    </nav>
                    <?php endif; ?>
                    <h5><?php echo $translate('Resources') ?></h5>
                    <?php echo $resourceNav; ?>
                    <?php if ($adminNav): ?>
                    <h5><?php echo $translate('Admin') ?></h5>
                    <?php echo $adminNav ?>
                    <?php endif; ?>
                    <?php if ($moduleNav): ?>
                    <h5><?php echo $translate('Modules') ?></h5>
                    <?php echo $moduleNav ?>
                    <?php endif; ?>
                </nav>
            </header>
            <script>
                $('#advanced').click(function(event) {
                    event.preventDefault();
                    $('#advanced-options').slideToggle('slow');
                });
            </script>

            <div id="content" role="main">
                <?php echo $this->messages(); ?>
                <?php echo $this->content; ?>
            </div>
        </div>
        <footer>
            <p class="site-version"><a href="https://omeka.org/s"><?php echo $translate('Omeka S'); ?></a> <span class="version-number"><?php echo sprintf($translate('version %s'), Omeka\Module::VERSION)?></span></p>
            <a href="<?php echo $this->url('admin/default', ['controller' => 'system-info']); ?>"><?php echo $translate('System information'); ?></a>
            <a href="https://omeka.org/s/docs/user-manual"><?php echo $translate('User manual'); ?></a>
            <a href="https://forum.omeka.org/"><?php echo $translate('Support forums'); ?></a>
        </footer>
    </body>
</html>
